import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  MatButtonModule,
  MatMenuModule,
  MatToolbarModule,
  MatIconModule,
  MatCardModule,
  MatListModule,
  MatFormFieldModule,
  MatCheckboxModule,
  MatRadioModule,
  MatInputModule,
  MatSidenavModule,
  MatExpansionModule,
  MatTabsModule,
  MatBottomSheetModule,
  MatDialogModule,
  MatTooltipModule,
  MatProgressBarModule,
  MatTableModule,
  MatSelectModule,
  MatPaginatorModule,
} from '@angular/material';
import { LayoutModule } from '@angular/cdk/layout';
import { FlexLayoutModule } from '@angular/flex-layout';

@NgModule({
  imports: [
    CommonModule,
    LayoutModule,
    FlexLayoutModule,
    MatButtonModule,
    MatMenuModule,
    MatToolbarModule,
    MatIconModule,
    MatCardModule,
    MatListModule,
    MatFormFieldModule,
    MatCheckboxModule,
    MatRadioModule,
    MatInputModule,
    MatSidenavModule,
    MatExpansionModule,
    MatTabsModule,
    MatBottomSheetModule,
    MatDialogModule,
    MatTooltipModule,
    MatProgressBarModule,
    MatTableModule,
    MatSelectModule,
    MatPaginatorModule,
  ],
  exports: [
    LayoutModule,
    FlexLayoutModule,
    MatButtonModule,
    MatMenuModule,
    MatToolbarModule,
    MatIconModule,
    MatCardModule,
    MatListModule,
    MatFormFieldModule,
    MatCheckboxModule,
    MatRadioModule,
    MatInputModule,
    MatSidenavModule,
    MatExpansionModule,
    MatTabsModule,
    MatBottomSheetModule,
    MatDialogModule,
    MatTooltipModule,
    MatProgressBarModule,
    MatTableModule,
    MatSelectModule,
    MatPaginatorModule,
  ]
})
export class UIModule { }
